import pytest

from app.arabic_money import amount_ar

# Expected strings are written out by hand from the standard rules of العدد
# والمعدود (number-noun agreement: 3-10 opposite gender + genitive plural,
# 11-99 accusative singular, 100s/1000s genitive singular, 1 and 2 said by the
# noun), not generated by the code under test or by num2words.


@pytest.mark.parametrize(
    ("price", "currency", "expected"),
    [
        ("450", "JOD", "450 (أربعمائة وخمسون) ديناراً أردنياً"),
        # The live regression: fils-precision zeros, read as 450 thousand.
        ("450.000", "JOD", "450 (أربعمائة وخمسون) ديناراً أردنياً"),
        ("1", "JOD", "1 (دينار أردني واحد)"),
        ("2", "JOD", "2 (ديناران أردنيان)"),
        ("3", "JOD", "3 (ثلاثة) دنانير أردنية"),
        ("11", "JOD", "11 (أحد عشر) ديناراً أردنياً"),
        ("100", "JOD", "100 (مائة) دينار أردني"),
        ("1250", "ILS", "1250 (ألف ومائتان وخمسون) شيكلاً جديداً"),
        ("450.500", "JOD", "450 (أربعمائة وخمسون) ديناراً أردنياً و500 (خمسمائة) فلس"),
        ("1000000", "USD", "1000000 (مليون) دولار أمريكي"),
        ("1003", "JOD", "1003 (ألف وثلاثة) دنانير أردنية"),
        ("2000", "USD", "2000 (ألفان) دولار أمريكي"),
        ("13000", "JOD", "13000 (ثلاثة عشر ألفاً) دينار أردني"),
        ("200000", "JOD", "200000 (مائتا ألف) دينار أردني"),
        ("1500000", "USD", "1500000 (مليون وخمسمائة ألف) دولار أمريكي"),
        ("300", "EUR", "300 (ثلاثمائة) يورو"),
        ("99.99", "EUR", "99 (تسعة وتسعون) يورو و99 (تسعة وتسعون) سنتاً"),
        # أغورة is feminine, so the number flips: خمس not خمسة, إحدى عشرة not أحد عشر.
        ("1250.05", "ILS", "1250 (ألف ومائتان وخمسون) شيكلاً جديداً و5 (خمس) أغورات"),
        ("0.11", "ILS", "11 (إحدى عشرة) أغورة"),
        ("0.28", "ILS", "28 (ثمانٍ وعشرون) أغورة"),
        ("0.01", "ILS", "1 (أغورة واحدة)"),
    ],
)
def test_amount_ar(price, currency, expected):
    assert amount_ar(price, currency) == expected


@pytest.mark.parametrize(
    ("price", "currency"),
    [
        ("450", "GBP"),  # no Arabic name on file
        ("450", None),
        (None, "JOD"),
        ("four hundred", "JOD"),
        ("0", "JOD"),
        ("-450", "JOD"),
        ("NaN", "JOD"),
        ("450.5555", "JOD"),  # finer than a fils
        ("1250.005", "ILS"),  # finer than an agora
        ("1000000000000", "USD"),
    ],
)
def test_amount_ar_declines_what_it_cannot_state_exactly(price, currency):
    assert amount_ar(price, currency) is None
